# Generated by Django 5.0.3 on 2024-03-31 12:57

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(null=True, upload_to=mainapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='vendor',
            name='aadhar',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='gst',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
