# Generated by Django 5.0.3 on 2024-04-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainapp.product'),
        ),
    ]
