# Generated by Django 5.0.3 on 2024-04-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_productcategory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='mainapp.product'),
        ),
    ]
