# Generated by Django 5.0.3 on 2024-04-18 07:19

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_productevent_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.image_directory_path),
        ),
    ]
