# Generated by Django 5.0.3 on 2024-04-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Actve', 'Active'), ('Inactive', 'Inactive')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Actve', 'Active'), ('Inactive', 'Inactive'), ('Banned', 'Banned')], max_length=10, null=True),
        ),
    ]
