# Generated by Django 5.0.3 on 2024-05-15 18:31

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_productspecification_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.website_images_path),
        ),
    ]
