# Generated by Django 5.0.3 on 2024-06-21 06:10

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_category_image_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='aadhar',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.vendor_directory_path),
        ),
    ]
