# Generated by Django 5.0.3 on 2024-06-28 06:33

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_chatbox_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.models.website_chats_path),
        ),
    ]
