# Generated by Django 5.0.3 on 2024-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_chatcontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
