# Generated by Django 5.0.3 on 2024-06-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_chatcontent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbox',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_customer', to='mainapp.customer'),
        ),
        migrations.AddField(
            model_name='chatbox',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_vendor', to='mainapp.vendor'),
        ),
        migrations.AlterField(
            model_name='chatbox',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_product', to='mainapp.product'),
        ),
    ]
