# Generated by Django 5.0.3 on 2024-06-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_chatbox_customer_chatbox_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_content', to='mainapp.chatbox'),
        ),
    ]
