# Generated by Django 5.0.3 on 2024-06-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_chatcontent_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbox',
            name='vendor',
        ),
    ]
